/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenuSistema = new javax.swing.JMenu();
        btnMenuCerrarSesion = new javax.swing.JMenuItem();
        btnMenuSalir = new javax.swing.JMenuItem();
        btnMenuProductos = new javax.swing.JMenu();
        btnMenuNuevo = new javax.swing.JMenuItem();
        btnMenuAdministrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        btnMenuSistema.setText("Sistema");

        btnMenuCerrarSesion.setText("Cerrar Sesion");
        btnMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCerrarSesionActionPerformed(evt);
            }
        });
        btnMenuSistema.add(btnMenuCerrarSesion);

        btnMenuSalir.setText("Salir");
        btnMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSalirActionPerformed(evt);
            }
        });
        btnMenuSistema.add(btnMenuSalir);

        jMenuBar1.add(btnMenuSistema);

        btnMenuProductos.setText("Productos");

        btnMenuNuevo.setText("Nuevo ");
        btnMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuNuevoActionPerformed(evt);
            }
        });
        btnMenuProductos.add(btnMenuNuevo);

        btnMenuAdministrar.setText("Administrar");
        btnMenuAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAdministrarActionPerformed(evt);
            }
        });
        btnMenuProductos.add(btnMenuAdministrar);

        jMenuBar1.add(btnMenuProductos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAdministrarActionPerformed
        ProductoAdmin a = new ProductoAdmin ();
        contenedor.add(a);
        a.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btnMenuAdministrarActionPerformed

    private void btnMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCerrarSesionActionPerformed
       int sel = JOptionPane.showConfirmDialog(this, " Desea cerrar sesion? ", " Cerrar Sesion ", JOptionPane.YES_NO_OPTION);
       if (sel==JOptionPane.YES_OPTION) {
       login l = new login();
       l.setVisible(true);
       this.dispose();
       
       }
       
       
       
       
        
        
        
    }//GEN-LAST:event_btnMenuCerrarSesionActionPerformed

    private void btnMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSalirActionPerformed
        int sel = JOptionPane.showConfirmDialog(this, " ¿Desea salir de la aplicacion ?", "Salir",JOptionPane.YES_NO_OPTION);
        
        if (sel==JOptionPane.YES_OPTION){
        System.exit(0);
        
        }
    }//GEN-LAST:event_btnMenuSalirActionPerformed

    private void btnMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuNuevoActionPerformed
        ProductoAgregar agr = new ProductoAgregar();
        panel.contenedor.add(agr);
        agr.setVisible(true);
        
    }//GEN-LAST:event_btnMenuNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnMenuAdministrar;
    private javax.swing.JMenuItem btnMenuCerrarSesion;
    private javax.swing.JMenuItem btnMenuNuevo;
    private javax.swing.JMenu btnMenuProductos;
    private javax.swing.JMenuItem btnMenuSalir;
    private javax.swing.JMenu btnMenuSistema;
    public static javax.swing.JDesktopPane contenedor;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
